#FIND_PATH(LIBUV_INCLUDE_DIR NAMES uv.h)
FIND_LIBRARY(MAPNIK_LIBRARIES NAMES mapnik libmapnik)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBMAPNIK DEFAULT_MSG MAPNIK_LIBRARIES)
