#FIND_PATH(LIBUV_INCLUDE_DIR NAMES uv.h)
FIND_LIBRARY(ICUUC_LIBRARIES NAMES icuuc libicuuc)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBICUUC DEFAULT_MSG ICUUC_LIBRARIES)
